name = "postie-worker"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[[d1_databases]]
binding = "DB"
database_name = "postie-db"
database_id = "606cb43f-af05-414b-88d0-2da2f781cfb7"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "postie-images"

[vars]
ALLOWED_ORIGINS = "https://postie-dashboard.pages.dev"
CLERK_JWKS_URL  = "https://sharp-rhino-4.clerk.accounts.dev/.well-known/jwks.json"
FACEBOOK_APP_ID = "9034587649978676"
R2_PUBLIC_URL = ""
CLIPY_API_URL = "https://clipy.blog/api"
